### PR TITLE
preconditioner update in bfgs and reverting weight computation for incremental BFGS

### PR DESCRIPTION
**Pull request by tzukuoh**
Updated bfgs.cc 
(1) Preconditioner is recomputed every pass
(2) Added reverting weight computation in test-only mode with input_feature_regularizer. The formula are based on approximate reverting weight for incremental BFGS.
(3) Fixed a bug in output_feature_regularizer computation.

### CODE REVIEW

**Comment by JohnLangford** [comment]
Can you verify that this change is neutral or improving w.r.t. demo/advertising?

**Comment by tzukuoh** [comment]
I think (1) and (2) are more neutral than improving.
(3) is a bug fix, so should be improving.

**Comment by JohnLangford** [comment]
It would be good to verify this.  I've gotten into trouble in the past 
with changes to the lbfgs code.

-John

**Comment by JohnLangford** [comment]
Ping on this?

**Comment by tzukuoh** [comment]
Any suggestion on how to verify?

**Comment by JohnLangford** [comment]
Run on demo/advertising and demo/dna.

-John

**Comment by tzukuoh** [comment]
It seems neutral.

time demo/advertising/naive_baseline.py

New:
Average test log likelihood: 0.407467
real    84m18.059s
user    114m15.592s
sys     16m17.733s

Old:
Average test log likelihood: 0.407562
real    81m17.888s
user    110m2.869s
sys     16m55.635s


demo/dna/make dna.perf  

New:
Net time taken by process = 703.108000 seconds
ACC    0.99744   pred_thresh  0.000000
APR    0.51307
ROC    0.97729

Old:
Net time taken by process = 734.418000 seconds
ACC    0.99744   pred_thresh  0.000000
APR    0.51307
ROC    0.97729

**Comment by JohnLangford** [comment]
What is "finalize reverting weight" supposed to be/do?

**Comment by tzukuoh** [comment]
I've currently implemented the batch reverting weight calculations for log-loss and squared loss.
The calculations have a common part, which is |w' x| / (x' R^{-1} x), where w is the existing weight vector and R is the diagonal regularizer. But they differ in multiplicative constants, and "finalize reverting weight" handles that.

**Comment by tzukuoh** [comment]
Closing this pull request and starting a new one #887 from a separate branch.

**Pull request closed without merging**
