### PR TITLE
Interact

### PR DESCRIPTION
**Pull request by alekh**

### CODE REVIEW

**Comment by JohnLangford** [comment]
This doesn't merge right now.  Can you fix?

Also, looking through the code:
1) Please comment out the debug flags in the Makefile.
2) Why is there a giant change to vw_static.vcxproj?
3) Can you add a test case to exercise the functionality please?

**Comment by alekh** [comment]
Fixed all issues. I am a tiny bit unsure about the correct way of adding
test case to Runtests, so please review. I am not on a linux machine right
now, so I cannot run make test myself.

Alekh

**Comment by JohnLangford** [comment]
The build is failing---you need to pass a flag to csoaa_ldf 
https://travis-ci.org/JohnLangford/vowpal_wabbit/builds/62726161

**Comment by alekh** [comment]
Done.

Alekh

**Comment by JohnLangford** [comment]
You need to check in the reference file:
https://travis-ci.org/JohnLangford/vowpal_wabbit/builds/62736575

-John

**Comment by alekh** [comment]
ugh...filename mismatch. Hope it works this time :)

Alekh

**Comment by JohnLangford** [comment]
Still broken.

https://travis-ci.org/JohnLangford/vowpal_wabbit/builds/62738079

-John

**Comment by alekh** [comment]
Should work now.

Alekh

**Comment by JohnLangford** [comment]
Still not there.

-John

**Comment by alekh** [comment]
This is odd. I get the loss values correctly reported when I run on my
windows command line. Travis gets loss values reported of 0. Let me try ssh
on my desktop and run make test there, if I don't get too much latency.

Alekh

**Comment by alekh** [comment]
There was an actual logic issue in loss computation. This has been fixed
now, and make test runs in linux. Things should work ideally.

Alekh

**Comment by sharatsc** [comment]
Build seems to have broken 
https://travis-ci.org/JohnLangford/vowpal_wabbit/builds/62766591
https://travis-ci.org/JohnLangford/vowpal_wabbit/builds

**Comment by JohnLangford** [comment]
That seems to have been some travis (i.e. not VW) fail.  Appveyor is still
barfing:

https://ci.appveyor.com/project/JohnLangford/vowpal-wabbit/build/1.0.30#L505

Any ideas how to fix?  We've been unable to reproduce locally.

-John

**Comment by JohnLangford** [comment]
Appveyor also seems to be _sometimes_ working.

https://ci.appveyor.com/project/JohnLangford/vowpal-wabbit/build/1.0.29#L5641

(i.e. there is a heisenbug)

-John

**Comment by sharatsc** [comment]
My Guess is that appveyor is timing out on the compile. I am trying to break up VW_static .vcxp to test this.

**Comment by JohnLangford** [comment]
Ok, thanks for investigating.

-John

**Pull request merged**
