### PR TITLE
adding support for probabilities flag in pyvw and sklearn_vw

### PR DESCRIPTION
**Pull request by gramhagen**
addressing problem identified in #1113 

pyvw.vw can provide a list of probabilities if initialized with --oaa and --probabilities
- python/tests/test_pyvw::test_oaa_probs()

similarly sklearn_vw.VW can provide a 2D numpy array of probabilities
- python/tests/test_sklearn_vw::test_oaa_probs()

### CODE REVIEW

**Comment by JohnLangford** [comment]
This is unquestionably an improvement, but it would be better if the prediction was controlled by the prediction type rather than the label type since these are not always in correspondence and that lack of correspondence will drive constant "oops, need to fix this" types of issues.  For example, I just added "scores" to oaa.cc which also returns a vector.

The prediction type is recorded in the top level predictor here: https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/learner.h#L114 and can be accessed via all->l.pred_type.

**Comment by gramhagen** [comment]
Yep makes sense. There are a few issues circling this area. I'll rework it
to use the prediction type.

**Comment by gramhagen** [comment]
@JohnLangford, wanted to make sure you saw the updates. this should be all set now. I based the changes on the approach used in the jni wrapper to leverage the prediction type

**Comment by JohnLangford** [comment]
Merged, thank you.

**Pull request merged**
