### PR TITLE
simd_fixes_from_ms

### PR DESCRIPTION
**Pull request by bscottm**
Minor tweaks to MSR-annotated fixes (constexpr not supported yet, a couple of places where the SIMD code should be conditionally compiled.)

Basically, when I drop the ARM SIMD code in, shouldn't have issues related to x86-specific conditional compilation.

### CODE REVIEW

**Comment by bscottm** [comment]
And some warning reduction related to clang and gcc (some of which were generated in the Travis CI 'make' output, BTW)

**Comment by JohnLangford** [comment]
Nick, can you take a look at this?

-John

**Comment by JohnLangford** [comment]
This patch seems good to go, except I don't understand what the changes to vwdll are buying us.  Why do them?

**Comment by JohnLangford** [comment]
I've merged this, except for the vwdll changes.

**Pull request merged**
