### PR TITLE
Fix clang format %llu vs arg (unsigned long or size_t) type warnings:…

### PR DESCRIPTION
**Pull request by arielf**
… #895

Affected files:
    - vowpalwabbit/gd.cc
    - vowpalwabbit/log_multi.cc
    - vowpalwabbit/search.cc

### CODE REVIEW

**Comment by JohnLangford** [comment]
I'm planning to fix this a different way.  In particular, I believe stringstream is more standardized across platforms.

**Comment by JohnLangford** [comment]
Ok, this is (hopefully) permanently fixed in the master now.   In 
essence, I replaced a massive number of printf's with stringstream's.  
All the tests are checking out, but I'd like Alex to take a look at this 
line:

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_regressor.cc#L245

and tell me if it is correct.

-John

**Comment by trufanov-nok** [comment]
If I recall right the `%.*s` is a [string of a known size, and its size is passed via parameter too](http://stackoverflow.com/questions/13289315/sprintf-usage-with-s).  

And `<< all.interactions[i].begin;` expecting a simple null terminated string. 
So there are two problems:  
1. Technically, there might be interactions with null namespace.
2. The all.interactions[i].end might not point to null. I think even when memory is allocated with calloc there might be a cases when you can get non-null bytes after real end of array. 

I think you should convert content of v_array to std::string with constructor `string (const char* s, size_t n);` ([string can contain embedded nulls](http://stackoverflow.com/questions/2845769/can-a-stdstring-contain-embedded-nulls)) and then write string to stream. I [expect it](http://stackoverflow.com/questions/19575173/how-to-copy-a-string-with-multiple-null-characters-to-a-stringstream) to be correctly written to stream in this case.

**Comment by JohnLangford** [comment]
I guess this is fixed now but for the record the correct specifier for
size_t types is %z which should work for all sizes of size_t. I'm not 100%
sure which version of MSVC is required to support it but it should be part
of C++11 support (and C99).

**Comment by JohnLangford** [comment]
Thanks.

This is the elegant fix, I think.  Yes?

https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/parse_regressor.cc#L247

-John

**Comment by trufanov-nok** [comment]
Yes, this is a better solution.

**Pull request closed without merging**
