### PR TITLE
temporary fix for segfault in word_alignment

### PR DESCRIPTION
**Pull request by hal3**

### CODE REVIEW

**Comment by marcovzla** [comment]
This segfault should have been fixed in 8d56ede968a2bb73cce181f2655d74b71a850b57

**Comment by JohnLangford** [comment]
There is an unreconciled patch in the diff.

**Comment by hal3** [comment]
sorry fixed!

**Comment by JohnLangford** [comment]
What is search_generate? 

Why do all of the tests use --search_linear_ordering?  Does that work better?  If so maybe that should be the default?  If not, maybe the tests should shift?

Where are the magic numbers in passthrough coming from?  Did passthrough prove useful?  Maybe the magic numbers should be encapsulated in a function call so they aren't all over the place?

**Comment by hal3** [comment]
search_generate is playing around with text generation. i can remove it but it's a reasonable example of using the library to roll your own search problem. let me know what you prefer.

the tests use --search_linear_ordering so that their output remained the same. in general our expectation is that it's better to leave this off.

magic numbers: they're just random large numbers. so far i haven't found passthrough to be particularly useful, but i wanted to try it on dep parsing because the other problems are very easy. i can move this all into a function call.

**Comment by JohnLangford** [comment]
A fair number of people use the test examples as documentation, so it seems better to update the test examples rather than use --search_linear_ordering.  

W.r.t. magic numbers, it seems better to use the standard feature generation technique.  Look here:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/interactions.h#L167 and on line 177.  Essentially, it is FNV_PRIME * first ^ second.  This one has been tested pretty thoroughly with evidence that it is better than a random number.

It seems even better to just use the existing feature manipulation.  Can you just add a pair for -q instead?

**Comment by hal3** [comment]
this is all fixed now. i did some __FILE__ magic in passthrough. let me know if you prefer another solution. the issue is that different reductions add their own passthrough info, but the feature ids need to not collide across reductions --> i needed some way to identify the reduction the passthrough was coming from.

**Comment by hal3** [comment]
not sure why appveyor failed -- it seems to be timing out.

**Comment by JohnLangford** [comment]
@eisber Do you know why AppVeyor is dieing here?

**Comment by eisber** [comment]
I had a similar issue. Just re-running the build fixed it.
We should actually looking into switching to VSO…

From: John
Reply-To: JohnLangford/vowpal_wabbit
Date: Friday, October 2, 2015 at 14:54
To: JohnLangford/vowpal_wabbit
Cc: Markus Cozowicz
Subject: Re: [vowpal_wabbit] temporary fix for segfault in word_alignment (#717)


@eisber<https://na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fgithub.com%2feisber&data=01%7c01%7cmarcozo%40064d.mgd.microsoft.com%7ce2c2309df2234d69e3b308d2cb5ae346%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=43DBq0Fr0EUMofeZ52FFfjpRc7TFM6cPhLZJNUOAnHc%3d> Do you know why AppVeyor is dieing here?

**Comment by JohnLangford** [comment]
Appveyor does seem pretty flaky.

Hal, can you bump it to cause a rebuild?

-John

**Comment by eisber** [comment]
I don’t have permissions so I don’t see the button, but for my pull request in appveyor it had a re-run button.

Markus

From: John
Reply-To: JohnLangford/vowpal_wabbit
Date: Friday, October 2, 2015 at 15:06
To: JohnLangford/vowpal_wabbit
Cc: Markus Cozowicz
Subject: Re: [vowpal_wabbit] temporary fix for segfault in word_alignment (#717)

Appveyor does seem pretty flaky.

Hal, can you bump it to cause a rebuild?

-John

**Comment by hal3** [comment]
done

**Comment by hal3** [comment]
urgh no it won't work because there were edits in the interim.

**Comment by hal3** [comment]
ok tried again

**Comment by JohnLangford** [comment]
Should we remove the --search_linear_ordering from the test cases (and update the outputs)?

Basically, do we want to see that forever after when people try things?

**Comment by JohnLangford** [comment]
Wow, the FILE hack is pretty impressive :-)

But why use (i+magic)*quadratic_constant?  This seems a worse index generation than the old quadratic features?

Why not (FNV_PRIME * magic) ^ i?

**Comment by hal3** [comment]
I'm not sure I should consider "pretty impressive" as positive or negative sentiment :). Really what's needed is for reductions to be able to identify themselves. I think this comes up in other places too -- like search should be able to check whether you have an LDF-based or non-LDF-based reduction underneath it. Anyway, end of tangent, this hack works for now.

I've changed it to FNV_prime and the xor business. I have to move the FNV_prime definition from interations.h to constant.h but that seems pretty reasonable.

Will re-push in aminute

**Comment by JohnLangford** [comment]
Cool.  Now should the --search_linear_ordering be left in?

**Comment by hal3** [comment]
ugh i thought I had changed that. I think git changed it back. give me another quick second :)

**Comment by hal3** [comment]
looks like it's good now

**Comment by JohnLangford** [comment]
Merged in, thanks.

-John

**Pull request merged**
