### PR TITLE
Test for -q :: & --invert_hash + support of comparision of arbitrary files in RunTests

### PR DESCRIPTION
**Pull request by trufanov-nok**
I've tried to create a test case to cover 2 issues:
#648 - we don't have any test to compare --invert_hash results
#649 -  we don't have any test that uses namespaces with wildcards like -q ::

So I've added following command line as a test:
`echo -e '3 |f a b c |e x y z\n2 |f a y c |e x' | {VW} --oaa 3 -q :: --invert_hash inv_hash.cmp`

Notice, it uses `echo` and pipeline instead of file as dataset.
Still I've added 2 files - for stdout and  inv_hash.cmp.

Regarding the last one - it looks like RunTests script decides what to compare by filename extension and parameter name. For example, `*.predict` is compared with whatever is used after `-p`. `*.stderr` with vw stderr etc.
I've decided not to specify new file extension for `--invert_hash` (as it's the only case among 88 tests) but declare one general use extension.
Now RunTests supports *.cmp extension. It will find whatever ends with .cmp in VW arguments list (as it's generic I cant rely on parameter name) and compare it with *.cmp in list of reference files.

As I don't know Perl I would like to ask @arielf  to verify the code if John confirms this is the enhancement script needs. I especially worry about case when both `-p sometheng.predict` and `--whatever *.cmd` are declared in VW command line. Won't `-p` regexp empty command line before `cmd` regexp process it? I'm not sure how =~ works.

### CODE REVIEW

**Comment by trufanov-nok** [comment]
It seems that Travis CI demonstrates inconsistence of my interactions filtering function. In one cases interaction '' A" is left and "A " in other. I'll try to fix that and include patch in this PR. In case this PR won't be possible to merge (there are might be also problems with weights comparison in model files that could fluctuates) I'll submit it as separate PR.

**Comment by arielf** [comment]
Thanks Alex,

My fault for not abstracting the reference-files in a nicer way.  There are very few vw options that produce a user-specified readable text file that can be compared: (`-p, --readable_model, --invert_hash, --output_feature_regularizer_text `) .  I feel it would be cleaner if we could 1) support all of them in a consistent way and 2) support multiple instances on the same line so all of them can be compared if they appear in the test.

What would be a clean abstraction to support this?  Is the `*.cmp` naming convention the best choice?  What about multiple `*.cmp` files?

To answer your questions:
`if ($string =~ /regexp/) ...` in perl is simply a pattern-matching statement, where the first (leftmost) match applies, but you can also do it in some loop to support multiple matches:
   `while ($string =~ /regexp/g) ...`
The `g` modifier will iterate on all matches so you can capture sub-matches (say in `$1`) and use them in the loop.

**Comment by trufanov-nok** [comment]
>  Is the *.cmp naming convention the best choice? 
nope
> What about multiple *.cmp files?
not supported.
My Perl knowledge doesn't allow me to implement better solution, I just though *.cmp approach is a bit better than extension supporting just invert_hash with same amount of code.

As for real generic approach: how about matching all files with reference files by extension. For example:
{VW} -d dataset.dat -p output.xxx --invert_hash 123.yyy
prediction_ref.xxx
invert_hash_ref.yyy

So .dat will be ignored as has no pair. xxx and yyy will be compared with their ref. .stderr and .stdout might be left as standard hardcoded extensions for VW's stderr and stdout.

**Comment by trufanov-nok** [comment]
And now i'm running into a problem of comparing files containing weights which might differ in 10^-5 - Travis CI failed. That somehow solved for stderr will take a look into code.

**Comment by trufanov-nok** [comment]
Hey, Ariel
Is it possible to allow control over lines slit in diff() before smart comparison (that takes precession into account) ? Suppose this would require passing additional argument (regexp string) to diff() and to diff_lenient_float() in it. By default it could be "/\s*\|\s*/". I would like to pass "/\s*\:\s*/" or even "/\s*\:[.+-0-9]*$/ in my last test case. My lines are in form of:
```
-e^x:125152:-0.078247
+e^x:125152:-0.078248
```
So only last piece should be compared. Of  course mismatch in 125152 will be more than precession so splitting just by ':' would be fine too.
And most inconvenient - such solution will require specification of new keyword in tests section that could let user to pass non-default regexp.
For example {SPLIT}[/\s*\:\s*/"] that could be parsed by `$line =~ /{SPLIT}[(\S+)]\b/`

**Comment by arielf** [comment]
Alex,

I'm not sure we need a different split regexp.
If there's a difference in any outputs (quick default diff), `RunTests` falls back to 'fuzzy-compare' where small precision differences are ignored.  This second fuzzy diff is very slow, and (always) calling `diff` with:
```
 -y, --side-by-side
              output in two columns
```
which always uses the `    |    ` separator between the two versions.

What may be a problem here is the _width_ of the line (not sure) which can be increased with `-W <somenumber>` See this line in `RunTests`:
```
my $DiffOpts = '-N --minimal --suppress-common-lines --ignore-all-space --strip-trailing-cr --side-by-side -W 160';
```
I hope to have more time to work on this the coming week. A bit swamped at the moment.

**Comment by trufanov-nok** [comment]
Ok, then I misunderstood the code. Then the word separators is the param I'm looking for. I'll try to do the adjustment by myself.
```
            # Break lines into tokens/words
            my (@w1) = split(' ', $line1);
            my (@w2) = split(' ', $line2);
```

**Comment by trufanov-nok** [comment]
Heh, it works!
Just using ':' instead of space as words separator was enough to apply diff() with precession adjustments for float values to text model file. I've added an optional `{WORD_SPLIT=x}` param that parsed in case `*.cmp` file was found. Where x is a split value which is = ' ' by default.

Would be great if you take a look and approve the code.

Fell free to modify these parameters later if you wish.

**Comment by trufanov-nok** [comment]
Ok, let's try global variable. I'm pretty fine with that.

**Comment by JohnLangford** [comment]
I'm going to merge this one in, as it seems clearly superior.  W.r.t. 
wildcard pairs, truncation has the potential to ignore some change in 
the definition of the wildcard set which seems potentially unfortunate.

Logically, we really only want a hard diff on this line.  Is that doable?

-John

**Pull request merged**
