### PR TITLE
fixed windows build

### PR DESCRIPTION
**Pull request by lhoang29**
Fixing build for the C++/CLI layer to work with new feature representation.

### CODE REVIEW

**Comment by JohnLangford** [comment]
Why is AppVeyor still barfing?

**Comment by lhoang29** [comment]
some unit tests are failing. I've been looking at it

**Comment by lhoang29** [comment]
fixed now

**Comment by JohnLangford** [comment]
Can you change "features.h" to be "feature_group.h"?

Also, is it possible to compile the cli stuff in linux?  (And automate that via Makefile? so that these sorts of changes are more automatic.)

**Comment by JohnLangford** [comment]
Merged.  I did the features.h -> feature_group.h change, but would still like to know the answer to the second question.

**Comment by lhoang29** [comment]
oh, I just checked in the rename as well, but maybe auto merge took care of it. 

As for the second question, I don't believe so. C++/CLI is a .NET specific language which requires the .NET CLR runtime and a compatible compiler. It seems there is a distribution of .NET on Linux (although I'm not sure what support it has). However the compiler is non-existent as far as I know.

**Comment by JohnLangford** [comment]
That's a little bit frustrating---it's very close to C++.

-John

**Pull request merged**
