### PR TITLE
Add --cubic regression test

### PR DESCRIPTION
**Pull request by arielf**
+ Left over commit I had in my master: small addition to the `vw-convergence` plotting utility: `-s` option to change point size.

### CODE REVIEW

**Comment by arielf** [comment]
All failures unrelated to my changes.

Test 140, marginal is a new heisenbug, exitcode 139 is SEGV.
I was able to reproduce only once in my env.

appveyor and java/maven build failures are also unrelated.

**Comment by JohnLangford** [comment]
yeah, the build fails need to be dealt with, but I'm out of time at the moment.

**Comment by JohnLangford** [comment]
There are conflicts though.  Can you fix that?

**Comment by arielf** [comment]
:) Conflict is because both Paul and I added a test to `RunTests` and he was merged first.
Let me remerge...

**Comment by arielf** [comment]
Should be mergable now  (failures still unrelated)

**Pull request merged**
