### PR TITLE
Add support for pkg-config

### PR DESCRIPTION
**Pull request by willnewton**
Add support for installing a pkg-config metadata file for VW libraries.

### CODE REVIEW

**Comment by JohnLangford** [comment]
What is the use case for this?

**Comment by JohnLangford** [comment]
Restated, if I break something, how will I know it?

**Comment by willnewton** [comment]
The use case is various bits of Linux software packaging machinery (and supposedly Mac and Windows but I haven't tested that):

http://www.freedesktop.org/wiki/Software/pkg-config/

It makes it much easier if you are building a program or library that depends on VW to just add PKG_CHECK_MODULES to your configure.ac and it will set the CFLAGS and LIBS correctly.

In terms of what the risks are of breaking things - if a new library dependency was added then the pkg-config file might need updating to take account of that, if it wasn't peoples builds would fail, hopefully they would report it and it would be fixed. It should be fairly low maintenance unless you anticipate large numbers of changes of that type.

**Comment by JohnLangford** [comment]
Ok, merged.   Library structure should not be changing too often.

-John

**Pull request merged**
