### PR TITLE
Cbify

### PR DESCRIPTION
**Pull request by alekh**

### CODE REVIEW

**Comment by JohnLangford** [comment]
@eisber why is the test failing here?

**Comment by eisber** [comment]
I’m checking if I can extract the arguments correctly again.
I merged Alekhs patches into my branch and updated a couple other things along. Can we discard this PR and I’ll create one?

**Comment by JohnLangford** [comment]
Merging from your branch is scary.   We can certainly do this, but only if
it does not create a large delay.

-John

**Comment by eisber** [comment]
Let me know how scary this one is: https://github.com/JohnLangford/vowpal_wabbit/pull/1013

Markus

**Comment by JohnLangford** [comment]
You didn't break github?  Clearly you are getting soft.

**Comment by JohnLangford** [comment]
I've merged this now because it has an additional bug fix.  I expect that git will do the right thing because your patch incorporates this one.

**Pull request merged**
