### PR TITLE
Improve Dep Parser and Entity-Relation Demo

### PR DESCRIPTION
**Pull request by KaiWeiChang**
Dep Parser:
- add a one_learer approach (at each step, choose parser action and arc label at once)
- support cost_to_go 
- increase the number of bits in demo to 30

Entity Relation Demo:
- Change the data format to a human readable format:
For example:

> 2 1.0 E_0:Peop|Feature  WORD_kane:1.0 POS_WINDOW_2IN:1.0 PHRASE_kane:1.0 BIAS:1.0 POS_WINDOW_1VBD:1.0 LEN_1:1.0
> 2 1.0 E_1:Peop|Feature  PER_:1.0 WORD_warner:1.0 POS_WINDOW_-1DT:1.0 PHRASE_warner:1.0 POS_WINDOW_1NN:1.0 POS_WINDOW_-2IN:1.0 BIAS:1.0 LEN_1:1.0
> 10 1.0 R_0_1:None|Feature  RPOS_WINDOW-2_IN:1.0 RP_LEX_warner:1.0 RPER_:1.0 REL_ENT_LEN_:9.0 RPOS_WINDOW1_NN:1.0 RP_LEN_1:1.0 LP_LEN_1:1.0 BIAS:1.0 LPOS_WINDOW1_VBD:1.0 RPOS_WINDOW-1_DT:1.0 LPOS_WINDOW2_IN:1.0 LP_LEX_kane:1.0

The performance of entity-relation improves:
Average Entity Recognition F1: 0.923702345513
Average Relation Recognition F1: 0.583242275596

### CODE REVIEW

**Comment by KaiWeiChang** [comment]
Any idea of these errors when it setups python library:
The command "python setup.py bdist_wheel" exited with 1.

**Comment by JohnLangford** [comment]
Huh.  Looks like make test_gcov is the first failure.  It's impressive that you have gcc segfaulting!

Maybe bump it to see if something fixes?  If not build make test_gcov in your environment to reproduce then debug?

**Comment by KaiWeiChang** [comment]
Hmm... It seems that we just had a bad luck. 
I made some minor style changes and forced travis to test it again. Then it passed. 

I also didn't see any problem when compiling it on my machine.

**Comment by JohnLangford** [comment]
All, this is in now.  Kai-Wei has substantially improved the dependency
parser.

-John

**Pull request merged**
