### PR TITLE
Nn pure reduction

### PR DESCRIPTION
**Pull request by pmineiro**
As discussed, nn not accessing weight vector directly.

### CODE REVIEW

**Comment by JohnLangford** [comment]
This fails on test 20.  Can you inspect and fix?

**Comment by pmineiro** [comment]
Changed random seed on test, works now.

**Comment by pmineiro** [comment]
Test 38 is a real bug, which I'm fixing, and then I want to re-run the demos (which will take a while).

**Comment by pmineiro** [comment]
Ok, demos seems stable.

**Pull request merged**
