### PR TITLE
updating python install tools

### LINKED ISSUE #1528: OSX boost-python find library error 'boost_python-mt'
Platform: OSX
Run: python setup.py test
Get Exception: Could not find boost python library

```
$ ls -l /usr/local/lib/ | grep boost_python
lrwxr-xr-x   1 gurin  admin   56 Jul 12 12:19 libboost_python27-mt.a -> ../Cellar/boost-python/1.67.0/lib/libboost_python27-mt.a
lrwxr-xr-x   1 gurin  admin   60 Jul 12 12:19 libboost_python27-mt.dylib -> ../Cellar/boost-python/1.67.0/lib/libboost_python27-mt.dylib
lrwxr-xr-x   1 gurin  admin   53 Jul 12 12:19 libboost_python27.a -> ../Cellar/boost-python/1.67.0/lib/libboost_python27.a
lrwxr-xr-x   1 gurin  admin   57 Jul 12 12:19 libboost_python27.dylib -> ../Cellar/boost-python/1.67.0/lib/libboost_python27.dylib
lrwxr-xr-x   1 gurin  admin   59 Jul 12 12:26 libboost_python37-mt.a -> ../Cellar/boost-python3/1.67.0_1/lib/libboost_python37-mt.a
lrwxr-xr-x   1 gurin  admin   63 Jul 12 12:26 libboost_python37-mt.dylib -> ../Cellar/boost-python3/1.67.0_1/lib/libboost_python37-mt.dylib
lrwxr-xr-x   1 gurin  admin   56 Jul 12 12:26 libboost_python37.a -> ../Cellar/boost-python3/1.67.0_1/lib/libboost_python37.a
lrwxr-xr-x   1 gurin  admin   60 Jul 12 12:26 libboost_python37.dylib -> ../Cellar/boost-python3/1.67.0_1/lib/libboost_python37.dylib
```

I think problem with this part of code in my case:
setup.py
```
        if sys.version_info.major == 2:
            boost_lib = 'boost_python-mt'
```

### PR DESCRIPTION
**Pull request by Scott-Graham-Bose**
to better handle boost dependencies across systems and under anaconda

no longer needs conda install script (instructions for conda added to README.rst)

improves resolution of python boost library, include, and ldflags used in building pyvwlib

tested under mac osx (python 2 and 3, and anaconda python 2 and 3) as well as ubuntu (python 2 and 3 and anaconda 2 and 3)

should fix #1528

### CODE REVIEW

**Comment by mlisovyi** [comment]
That should simplify life. The only issue is that it will break vw installation in the kaggle kernels docker image, which used the installation script. One will need to check if vw installs there painlessly as well (unfortunately, their docker image is HUGE and I got rid of it and all infrastructure, when i was swaping my laptop a few weeks ago :( )

**Comment by Scott-Graham-Bose** [comment]
ah good to know, is this something I can contribute to to correct on that side? if so where is the kernel you're referring to?

**Comment by mlisovyi** [comment]
yes, sure, contributions are very welcome. This is managed by a docker image, that is defined in a dedicated package on github. The vw installation takes place here:

https://github.com/Kaggle/docker-python/blob/332d8703dd6d7cb19a46482b3f8e26a2fe0014d6/Dockerfile#L509

There are instructions on how to use the image and test it in the README of the package

**Comment by JohnLangford** [comment]
github is not providing an option to update to the current master for this pull request?   I'll track it down manually if necessary, but do we know any reason why it should not allow that?

**Comment by Scott-Graham-Bose** [comment]
let me merge in the latest updates to master

**Comment by JohnLangford** [comment]
Merged, thanks :-)

**Pull request merged**
