### PR TITLE
Fix recent broken build also seen in OS-X

### PR DESCRIPTION
**Pull request by arielf**
Turned out to be a leading space introduced by C++ FP formatting of the 1st number in a line

`RunTests` now works-around this by stripping leading white space in lenient-float compares.

### CODE REVIEW

**Comment by arielf** [comment]
Also: this now passes test 16 with either `-march=native` or not.

**Comment by JohnLangford** [comment]
Great, thanks Ariel.  Getting macs to pass tests is a nice bonus.

-John

**Comment by arielf** [comment]
NP, sorry it took me so long to figure this out.  Once you discovered this can also be triggered by `-march=native` and I could reproduce it (with gcc only) on every try, I was able to figure out the root cause.

**Comment by JohnLangford** [comment]
Yeah, reproducibility is the key to solution.

-John

**Pull request merged**
