### PR TITLE
Fix bugs in cb_adf.cc

### PR DESCRIPTION
**Pull request by yitanms**

### CODE REVIEW

**Comment by JohnLangford** [comment]
The build is broken:

https://travis-ci.org/JohnLangford/vowpal_wabbit/builds/62321917

Can you fix?

**Comment by JohnLangford** [comment]
Can you get rid of 'array' and 'cs_label_array' now?

Why did you add predict back in?  It should be unnecessary.

**Comment by yitanms** [comment]
Sure.

Sent from my Windows Phone
________________________________

**Comment by JohnLangford** [comment]
Merged, thanks.

**Pull request merged**
