### PR TITLE
fixed operator #689

### PR DESCRIPTION
**Pull request by djstrong**
@JohnLangford operator fix in #689

### CODE REVIEW

**Comment by djstrong** [comment]
Segmentation fault in dep_parser is fixed too.

**Comment by JohnLangford** [comment]
This is failing a test.  Good? Bad? Why?

https://travis-ci.org/JohnLangford/vowpal_wabbit/builds/67062877

**Comment by djstrong** [comment]
I am sorry for not checking this.
There are 2 differences:
```
$ diff inv_hash.cmp pred-sets/ref/inv_hash.cmp 
1d0
< Version 7.10.2
7a7
> rank:0
```

**Comment by JohnLangford** [comment]
Fix please?

**Comment by djstrong** [comment]
After merging with head there is another test with dep parser. The change is in total feature number, I don't know if "my" changes should change that.

**Comment by trufanov-nok** [comment]
I've created a separate PR for operator issue:
https://github.com/JohnLangford/vowpal_wabbit/pull/696
As it affects test 88 too and shall be fixed asap, bcs changes model file format.

As for segfault I've noticed that @hal3 had fixed it 3 days ago
https://github.com/JohnLangford/vowpal_wabbit/commit/4b7515068a2d28f6afaaa1f0f0e276594d84cd8d
And his fix affected some test files too. 

With current master sourcecode and #696 applied to it test 65 works fine and gives 696025 total features.
Perhaps you got into a clinch between these commits.

**Comment by djstrong** [comment]
Thanks for cleaning it up, so you can delete this PR.

**Comment by trufanov-nok** [comment]
> Edit: or not, there is issue with dep_parser: djstrong@619f264

That file comparison should be some artefact bcs I already see the required fix in master code:
https://github.com/JohnLangford/vowpal_wabbit/blob/master/vowpalwabbit/search_dep_parser.cc#L63

**Comment by djstrong** [comment]
Ok, so this PR can be deleted.

**Pull request closed without merging**
