### PR TITLE
switch to new from malloc to get exception support

### PR DESCRIPTION
**Pull request by eisber**
Conflicts:
	vowpalwabbit/parser.cc

### CODE REVIEW

**Comment by JohnLangford** [comment]
I don't see a flaw.

-John

**Comment by JohnLangford** [comment]
Huh, travis build fails.

**Comment by eisber** [comment]
Pushed. Hopefully fixed.

From: John
Reply-To: JohnLangford/vowpal_wabbit
Date: Wednesday, October 7, 2015 at 17:12
To: JohnLangford/vowpal_wabbit
Cc: Markus Cozowicz
Subject: Re: [vowpal_wabbit] switch to new from malloc to get exception support (#814)


Huh, travis build fails.

**Comment by JohnLangford** [comment]
I used calloc_or_throw() instead to be more consistent with the rest of the codebase.  Let's have a separate discussion about the alloc/new debate.

**Pull request closed without merging**
