### PR TITLE
human friendly wrappers to use lda in vw

### PR DESCRIPTION
**Pull request by supertramped**
'vw-lda' is a friendly higher-level wrappers which allows the users to work directly on plain-text document collections and deal with all the leg-work this entails, automatically.

This wrapper does the following:
        - converts words to numeric features and numeric features back to words at the end
        - allows working on many docs at a time
        - support for Stop-word filtering (English only at this stage)
        - more friendly options handling
        - has reasonable defaults for all LDA options
        - more friendly/mnemonic options with usage help

### CODE REVIEW

**Comment by arielf** [comment]
Hi John,

I suggested to Chetan to contribute this, and iterated with him to bring it to a good 1st stage.

The impetus was the many questions on the mailing list related to how to run lda.  This contribution makes it real easy. The minimal-call is:    vw-lda -s <dir_with_text_docs>  or   vw-lda -f <file_list...>
plus, it exposes all the LDA parameters via usage.  Here's the usage message when no args are given:

```
$ vw-lda
usage: vw-lda [-h] (-f  [...] | -s ) [-t] [-n] [-b] [-a] [-r] [-e] [-o] [-m] [-mt]

Inputs for using vw with lda

optional arguments:
  -h, --help            show this help message and exit
  -f  [ ...], --file_list  [ ...]
                        List of input files separated by space
  -s , --src_dir        Directory containing input documents, defaults to current directory
  -t , --lda            Run lda with <int> topics, defaults to 100
  -n , --lda_D          Number of documents, defaults to 0, all files to be included
  -b , --bit_precision
                        Number of bits in the feature table, defaults to 18
  -a , --lda_alpha      Prior on sparsity of per document topic, defaults to 0.1
  -r , --lda_rho        Prior on sparsity of topic distributions, defaults to 0.1
  -e , --lda_epsilon    Loop convergence threshold, defaults to 0.1
  -o , --output_file    Output file which has the list of topics, defaults to op.model
  -m , --readable_model
                        Output human readable final regressor, defaults to hashed_lda_model.vw
  -mt , --max_terms     Max terms per topic to print on the console, defaults to 10
```

Thanks.

**Comment by sharatsc** [comment]
Related pull request that might affect this. Please take a look. This is the second attempt and would appreciate extra eyes. 
https://github.com/JohnLangford/vowpal_wabbit/pull/751

**Comment by JohnLangford** [comment]
Thanks Chetan.

If you can document the usage systematically, I believe that will
significantly increase usage.

-John

**Comment by supertramped** [comment]
Thanks John. I'll do what you suggested. I want to continue contributing to
VW.

Cheers
Chetan

**Pull request merged**
