### PR TITLE
Contextual_Bandit_Example_with_VW_Python_Wrapper

### PR DESCRIPTION
**Pull request by julian-runge**
The original notebook can be found here: https://colab.research.google.com/drive/1_t5ovcXL9pBhsC9YZXjPANGhQK2Kryvd#scrollTo=OPlledP-8oo9
Might be worthwhile to link to this file somewhere in https://github.com/JohnLangford/vowpal_wabbit/wiki/Contextual-Bandit-Example. I used the same sample data.

### CODE REVIEW

**Comment by Scott-Graham-Bose** [comment]
this looks good, but I would suggest a shorter filename, preferably without spaces or apostrophes as that might cause problems for some users / os's

thanks!

**Comment by julian-runge** [comment]
Adjusted filename per @Scott-Graham-Bose 's comment

**Comment by JohnLangford** [comment]
It looks like the patch was renamed but not the filename?  See here: 
https://github.com/julian-runge/vowpal_wabbit/blob/058fa99bdb315b6d48512f102cef00545173324f/python/examples/Implementing%20a%20Contextual%20Bandit%20Using%20VW's%20Python%20Wrapper.ipynb

**Comment by julian-runge** [comment]
@JohnLangford fixed, thanks for noting

**Comment by JohnLangford** [comment]
Merged, thanks.

**Pull request merged**
