### PR TITLE
Exposing tracing via API

### PR DESCRIPTION
**Pull request by eisber**
+ minor refactoring/cleanup for sparse/dense parameters

### CODE REVIEW

**Comment by JohnLangford** [comment]
What is the status of the appveyor fail?

**Comment by JohnLangford** [comment]
The void* and the not working on windows seem like the primary concerns here.

**Comment by eisber** [comment]
void* for the json parser? Looking into the Windows build.

Markus

**Comment by JohnLangford** [comment]
This is still failing in the appveyor build.  I'm going to merge on the theory that it is better than where we are right now, but fixing the appveyor build seems important.

**Pull request merged**
