### PR TITLE
Fix for Issue 960

### PR DESCRIPTION
**Pull request by gramhagen**
cleaning up predict call in sklearn_vw to use new predict method in pyvw
removing finish() there which causes segmentation fault when run predict, or score multiple times
added test to catch this case

### CODE REVIEW

**Comment by JohnLangford** [comment]
This seems to kill of the possibility of using the python interface for multiclass predictions?

**Comment by JohnLangford** [comment]
This seems like an improvement on what's their so I'm willing to incorporate it.  

However, the label type detection is still kindof buggy and prone to needing future fixes.    Do you think something like this: https://github.com/JohnLangford/vowpal_wabbit/blob/master/java/src/main/c%2B%2B/vw_learner_VWLearners.cc#L41 is feasible instead?

**Comment by gramhagen** [comment]
I can take a look and clean it up a bit.

scott

**Comment by gramhagen** [comment]
should be good now, take a look

**Comment by JohnLangford** [comment]
Merged.  Thanks for working through it!

**Pull request merged**
