### PR TITLE
ENH: singularity definitions

### PR DESCRIPTION
**Pull request by yarikoptic**
To assist with troubleshooting problems in 32bit (or 64 bit) Debian unstable environment, s came out from https://github.com/JohnLangford/vowpal_wabbit/issues/1410 needs.

You could (after installing singularity, on Debian apt-get install singularity-container, recent versions available from the NeuroDebian repository for older debian/ubuntus):

```shell
$ singularity pull shub://yarikoptic/vowpal_wabbit:debian-unstable-i386
$ singularity exec ./yarikoptic-vowpal_wabbit-master-debian-unstable-i386.simg make clean test
```
or just
```shell
$ ./yarikoptic-vowpal_wabbit-master-debian-unstable-i386.simg
```
to enter such an environment.  Your HOME would be mounted so you could continue working within your git clone etc.

If you decide to accept this PR, before then go to http://singularity-hub.org/, login via github, enable building images for this repo so you could get an "official" shub://JohnLangford/vowpal_wabbit instead of mine ;-)  Then  we could talk about making use of them on travis I guess

### CODE REVIEW

**Comment by JohnLangford** [comment]
Thanks @yarikoptic There is some setup that I need to do on my end, but I'm planning to work through VW backlog things for the next week.

**Comment by JohnLangford** [comment]
I merged and logged in.  What's next?

**Comment by yarikoptic** [comment]
If you are inside singularity 32bit, you can now build, test, troubleshoot 32bit tests failures at you would normally do (make etc, all dependencies should have been installed)

**Comment by JohnLangford** [comment]
Great.   Probably Monday.



On Wed, Mar 7, 2018 at 5:30 PM, Yaroslav Halchenko <notifications@github.com

**Pull request merged**
