### PR TITLE
Adding support for learning from Java, a test for it, and minor makefile...

### PR DESCRIPTION
**Pull request by EmergentOrder**
... changes to make compilation work

### CODE REVIEW

**Comment by JohnLangford** [comment]
Jonathan, can you take a look at this?

-John

**Comment by JohnLangford** [comment]
Jonathan (who made the first version) asks: can you consolidate things so there is less duplicate code?

**Comment by EmergentOrder** [comment]
removed duplication by factoring out string constant & a new function.

**Comment by JohnLangford** [comment]
Thanks, merging.

**Pull request merged**
