### PR TITLE
Getting Java compilation to work

### PR DESCRIPTION
**Pull request by jmorra**
While trying to make a release version of VW 8.2 I noticed that the Java build script was broken.  This commit fixes that issue.

### CODE REVIEW

**Comment by jmorra** [comment]
@deaktator could you have a look at this?

Thanks

**Comment by deaktator** [comment]
This looks good to me.  It seems like the `\s*` in the *sed* expressions in `build.sh` is much more robust than the spaces previously used.  I'm not sure what the semicolon does, but that's OK.  It looks like the point of the sed expression is to include the proper include path in case it's not `/usr/local/lib`.  Is this correct?  Maybe put a comment above line 46.

**Comment by jmorra** [comment]
@deaktator, you are correct the BOOST_LIBRARY needed to be more general to continue to work.  The other changes were simply stylistic.  @JohnLangford, do you think this is good to merge in?

**Comment by JohnLangford** [comment]
Yep.   Thanks.

**Pull request merged**
