### PR TITLE
Added a Doxyfile for use with doxygen.

### PR DESCRIPTION
**Pull request by danmelamed**
This can help new VW users to understand the code.

### CODE REVIEW

**Comment by JohnLangford** [comment]
How do you envision doxygen being used with the wiki?

**Comment by danmelamed** [comment]
Since code docs are only useful to the extent that they are up to date, they should ideally be updated automatically and associated with branches, rather than with static and manually updated info like the wiki.  Eventually, we can make doxygen run as part of the build process (at least some of the time) on a build server, and make its output browsable directly on the build server.  For now, devs can run it (`make doc`) and browse its output locally on their own machine.

**Comment by JohnLangford** [comment]
My understanding is that this is presently a noop, because no one is taking advantage of doxygen?  I'm hesitant to add things in until it actually does something useful.

**Comment by danmelamed** [comment]
Why do you think that nobody is taking advantage of doxygen?  I certainly am.

**Comment by JohnLangford** [comment]
I don't see any documentation in the path.  How does doxygen work?

-John

**Comment by danmelamed** [comment]
doxygen creates the documentation from the source code.  As with other resources that are generated by `make`, these docs are not checked into the repo.

To use, install doxygen and dot/graphviz on your machine, checkout this branch, type `make doc`, and then point your browser at doc/html/index.html .

Dan

**Comment by JohnLangford** [comment]
I see.  Hyperlinked code is pretty handy.  How do you make the start page for doxygen point to the wiki as an additional source of information?

**Comment by JohnLangford** [comment]
Maybe also add the Doxyfile to the doc directory?

**Comment by danmelamed** [comment]
both done

**Comment by JohnLangford** [comment]
Merged.  I'd like to setup hunch.net/~vw to have this also.  I'll look into it.

**Comment by JohnLangford** [comment]
Merged, thanks.  Also, now on http://hunch.net/~vw

-John

**Pull request merged**
