### PR TITLE
Add option to not regularize the intercept term for BFGS

### PR DESCRIPTION
**Pull request by arirang-pust**
This is a partial fix to #919.

### CODE REVIEW

**Comment by JohnLangford** [comment]
This seems reasonable to do, but having a branch on the inner loop is not very pleasant.  Can you instead record weights[constant_feature] externally and then subtract it off?

**Comment by JohnLangford** [comment]
This looks good now, except that it's violating modularity.  Can you put the parsing of arguments into bfgs.cc near the bottom and the storage into the bfgs datastructure?

**Comment by mikeizbicki** [comment]
The current implementation only works for bfgs, but this is something that in theory any optimizer could support.  If someone later adds this functionality to another optimizer, they'd have to undo the "modularization" and moving everything back where it currently is.  So I think it makes sense to leave these parts of the code as-is.

**Comment by JohnLangford** [comment]
Ok, I can live with that. 

I had to change multiple things to make this sensible.  Can you create a test case which confirms this option is working?

**Pull request merged**
