### PR TITLE
merged changes with exploration library to add log-by-default for tau-first

### PR DESCRIPTION
**Pull request by lhoang29**

### CODE REVIEW

**Comment by lhoang29** [comment]
@JohnLangford can you review?

**Comment by JohnLangford** [comment]
Overloaded today, but I will when I have time.

**Comment by JohnLangford** [comment]
Do we need the log_action variable any more?

Can you sync to current master?

**Comment by lhoang29** [comment]
No we don't need it, but since it doesn't affect anything and could be useful in the future I decided to leave it (for example I could see us trying to optimize logging).

**Comment by JohnLangford** [comment]
I think we should remove it on the theory that leaving dead code around is undesirable.

**Comment by JohnLangford** [comment]
Remove the bool?

**Comment by lhoang29** [comment]
Should we still log things when exploration is turned off? Or should we allow an option to log / not log? It might be also useful in this case to indicate whether the event was chosen in a deterministic fashion.

**Comment by JohnLangford** [comment]
The right view is that we always explore, and hence determinism should not
prevent logging.

Turning off logging as an option does seem reasonable.  Is there an
interface to do so?

-John

**Comment by lhoang29** [comment]
Yes there is already an interface to control logging. That's what I wanted to keep around. I can delete the extra local bools that do nothing (and always pass true into the logging interface).

**Comment by JohnLangford** [comment]
Deleting the extra but keeping the interface functional seems like a 
good idea.

-John

**Pull request merged**
