### PR TITLE
fix Visual Studio Build Errors and warning

### PR DESCRIPTION
**Pull request by nicknussbaum**
Add missing files to static lib project

fix build errors and some warnings

### CODE REVIEW

**Comment by JohnLangford** [comment]
Thanks.

**Comment by trufanov-nok** [comment]
Hi, I've found a problem with this PR. It's described here: https://github.com/JohnLangford/vowpal_wabbit/issues/574
There is one line to fix. Could someone pls reverse its change?

**Comment by nicknussbaum** [comment]
Sorry about that.

 

Can you verify that the following change works for you?

 

      for (size_t i = 0; i < 256; i++)

          all.redefine[i] = (unsigned char)i;

**Comment by trufanov-nok** [comment]
Yes, it works.
Btw, i've also [googled](http://stackoverflow.com/questions/13139621/looping-with-an-unsigned-char) the "elegant" solution for such problem:
```
      unsigned char i = 0;
      do {
          all.redefine[i] = i;
      } while (++i != 0);
```
But old one is shorter and more expectable. So unless someone think it faster I would stick with old loop.

**Comment by nicknussbaum** [comment]
The fix it’s to avoid the warning for the cast

 

I’ve submitted a pull request for the cast version.

 

I’m not wild about depending on the max size of char as the form you suggest.

I’d probably prefer the slightly slower

 

unsigned char  c = 0;

For ( int I = 0; I <255; ii++) {
                all.redefine[i] = c++;

}

 

Anyhow, sorry for bug.

**Comment by bscottm** [comment]
@JohnLangford, @trufanov-nok: I ran into this as well earlier. It's also in my pull request.

**Comment by bscottm** [comment]
It's not a good idea, defensively, to use unsigned char or char as an array index, which ought to be obvious by now.

**Comment by bscottm** [comment]
@JohnLangford: There were also undefined behavior warnings in parse_args.cc. Also in my pull request.

**Pull request merged**
