### PR TITLE
added [Serializable] attribute to exception

### PR DESCRIPTION
**Pull request by eisber**
This should fix the test cases

### CODE REVIEW

**Comment by JohnLangford** [comment]
Still failing?

**Comment by eisber** [comment]
Yes. Though my appveyor build works, the integration build doesn’t… Sigh
Still trying to figure out whats going on.

From: John
Reply-To: JohnLangford/vowpal_wabbit
Date: Friday, June 26, 2015 at 20:25
To: JohnLangford/vowpal_wabbit
Cc: Markus Cozowicz
Subject: Re: [vowpal_wabbit] added [Serializable] attribute to exception (#713)


Still failing?

**Comment by JohnLangford** [comment]
Something funky, clearly.

-John

**Comment by JohnLangford** [comment]
Merged in.  

Why is there so much CATCHRETHROW?   It seems you could just not catch things.

**Comment by eisber** [comment]
In C# I’m unable to access any members of the exception and the what() is not getting transferred to the default C# representation of the native exception (it’s getting wrapped anyway).
Thus I’m catching it in the CLI layer and wrap it manually so we get all the information (what(), file, linenumber).

Markus

From: John
Reply-To: JohnLangford/vowpal_wabbit
Date: Tuesday, June 30, 2015 at 09:08
To: JohnLangford/vowpal_wabbit
Cc: Markus Cozowicz
Subject: Re: [vowpal_wabbit] added [Serializable] attribute to exception (#713)


Merged in.

Why is there so much CATCHRETHROW? It seems you could just not catch things.

**Pull request merged**
