### PR TITLE
Unified source code style

### PR DESCRIPTION
**Pull request by martinpopel**
A suggestion how to solve #769.
I've added .editorconfig file and applied [`astyle`](http://astyle.sourceforge.net/) on the C++ source files as
```
astyle --lineend=linux --indent=spaces=2 *.cc *.h
```
I have not changed the bracketing style: attached (K&R, Stroustrup,...)  vs. broken (Allman, GNU,...). This could be unified with `astyle` with e.g. `--style=stroustrup` in future PR if we (well, John) decide on the preferred style for VW.

### CODE REVIEW

**Comment by JohnLangford** [comment]
Having a consistent style seems fine in general, but how do we enforce it
in the future?  It looks like most people likely will not have
.editorconfig readers by default since emacs and visualstudio don't use
that by default.

To me, style seems like a nice-to-have but not essential, so I'd prefer to
not have the enforcement mechanism be 'I reject patches'.  I realize this
is subjective, but the benefits of consistency are minor in my experience
compared to (say) the benefit of simplicity, good naming, conciseness,
etc...

There is also the 'which style' question w.r.t. the current patch.  I don't
have strong opinions about style, but I do find having one-liners
-void add_float(float& c1, const float& c2) { c1 += c2; }

more elegant than 3-liners.
+void add_float(float& c1, const float& c2) {
+c1 += c2;+}

and I tend to prefer the { } to either be all in the same line or all in
the same column to aid disambiguation.

Perhaps others who care should discuss any preferences they have?

-John

**Comment by sharatsc** [comment]
I vote to have only white space changes in this pull. Other changes will
break clean merges for everybody. We could run style during releases and
for frequent use (on *nix systems) checkin a commit hook (e.g.
https://gist.github.com/kblomqvist/bb59e781ce3e0006b644) that runs style
prior to commit.

regards
Sharat

On Wed, Sep 2, 2015 at 3:12 PM, John <notifications@github.com> wrote:

> Having a consistent style seems fine in general, but how do we enforce it
> in the future? It looks like most people likely will not have
> .editorconfig readers by default since emacs and visualstudio don't use
> that by default.
>
> To me, style seems like a nice-to-have but not essential, so I'd prefer to
> not have the enforcement mechanism be 'I reject patches'. I realize this
> is subjective, but the benefits of consistency are minor in my experience
> compared to (say) the benefit of simplicity, good naming, conciseness,
> etc...
>
> There is also the 'which style' question w.r.t. the current patch. I don't
> have strong opinions about style, but I do find having one-liners
> -void add_float(float& c1, const float& c2) { c1 += c2; }
>
> more elegant than 3-liners.
> +void add_float(float& c1, const float& c2) {
> +c1 += c2;+}
>
> and I tend to prefer the { } to either be all in the same line or all in
> the same column to aid disambiguation.
>
> Perhaps others who care should discuss any preferences they have?
>
> -John
>
> On Wed, Aug 26, 2015 at 4:30 AM, Martin Popel <notifications@github.com>
> wrote:
>
> > A suggestion how to solve #769
> > <https://github.com/JohnLangford/vowpal_wabbit/issues/769>.
> > I've added .editorconfig file and applied astyle
> > <http://astyle.sourceforge.net/> on the C++ source files as
> >
> > astyle --lineend=linux --indent=spaces=2 *.cc *.h
> >
> > I have not changed the bracketing style: attached (K&R, Stroustrup,...)
> > vs. broken (Allman, GNU,...). This could be unified with astyle with e.g.
> > --style=stroustrup in future PR if we (well, John) decide on the
> > preferred style for VW.
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/JohnLangford/vowpal_wabbit/pull/770
> > Commit Summary
> >
> > - more intuitive variable name
> > - typo: --raw -> --raw_predictions
> > - distinguish "feature weight" and "feature value"
> > - .editorconfig draft
> > - consistent indentation and style
> >
> > File Changes
> >
> > - *A* .editorconfig
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-0>
> > (27)
> > - *M* vowpalwabbit/accumulate.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-1>
> > (212)
> > - *M* vowpalwabbit/accumulate.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-2>
> > (2)
> > - *M* vowpalwabbit/active.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-3>
> > (222)
> > - *M* vowpalwabbit/active_interactor.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-4>
> > (202)
> > - *M* vowpalwabbit/allreduce.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-5>
> > (77)
> > - *M* vowpalwabbit/allreduce.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-6>
> > (92)
> > - *M* vowpalwabbit/autolink.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-7>
> > (24)
> > - *M* vowpalwabbit/beam.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-8>
> > (62)
> > - *M* vowpalwabbit/best_constant.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-9>
> > (111)
> > - *M* vowpalwabbit/best_constant.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-10>
> > (24)
> > - *M* vowpalwabbit/bfgs.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-11>
> > (978)
> > - *M* vowpalwabbit/binary.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-12>
> > (29)
> > - *M* vowpalwabbit/boosting.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-13>
> > (572)
> > - *M* vowpalwabbit/bs.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-14>
> > (380)
> > - *M* vowpalwabbit/bs.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-15>
> > (50)
> > - *M* vowpalwabbit/cache.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-16>
> > (158)
> > - *M* vowpalwabbit/cb.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-17>
> > (476)
> > - *M* vowpalwabbit/cb.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-18>
> > (40)
> > - *M* vowpalwabbit/cb_adf.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-19>
> > (788)
> > - *M* vowpalwabbit/cb_algs.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-20>
> > (715)
> > - *M* vowpalwabbit/cb_algs.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-21>
> > (66)
> > - *M* vowpalwabbit/cbify.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-22>
> > (522)
> > - *M* vowpalwabbit/comp_io.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-23>
> > (108)
> > - *M* vowpalwabbit/comp_io.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-24>
> > (10)
> > - *M* vowpalwabbit/cost_sensitive.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-25>
> > (485)
> > - *M* vowpalwabbit/cost_sensitive.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-26>
> > (36)
> > - *M* vowpalwabbit/csoaa.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-27>
> > (172)
> > - *M* vowpalwabbit/csoaa.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-28>
> > (4)
> > - *M* vowpalwabbit/ect.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-29>
> > (482)
> > - *M* vowpalwabbit/example.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-30>
> > (165)
> > - *M* vowpalwabbit/example.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-31>
> > (34)
> > - *M* vowpalwabbit/expreplay.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-32>
> > (15)
> > - *M* vowpalwabbit/ezexample.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-33>
> > (182)
> > - *M* vowpalwabbit/ftrl.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-34>
> > (71)
> > - *M* vowpalwabbit/gd.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-35>
> > (1209)
> > - *M* vowpalwabbit/gd.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-36>
> > (140)
> > - *M* vowpalwabbit/gd_mf.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-37>
> > (384)
> > - *M* vowpalwabbit/global_data.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-38>
> > (205)
> > - *M* vowpalwabbit/global_data.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-39>
> > (162)
> > - *M* vowpalwabbit/hash.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-40>
> > (76)
> > - *M* vowpalwabbit/hash.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-41>
> > (26)
> > - *M* vowpalwabbit/interact.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-42>
> > (38)
> > - *M* vowpalwabbit/interactions.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-43>
> > (597)
> > - *M* vowpalwabbit/interactions.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-44>
> > (517)
> > - *M* vowpalwabbit/io_buf.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-45>
> > (140)
> > - *M* vowpalwabbit/io_buf.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-46>
> > (142)
> > - *M* vowpalwabbit/kernel_svm.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-47>
> > (1320)
> > - *M* vowpalwabbit/label_dictionary.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-48>
> > (192)
> > - *M* vowpalwabbit/label_dictionary.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-49>
> > (30)
> > - *M* vowpalwabbit/lda_core.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-50>
> > (582)
> > - *M* vowpalwabbit/learner.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-51>
> > (88)
> > - *M* vowpalwabbit/learner.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-52>
> > (474)
> > - *M* vowpalwabbit/log_multi.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-53>
> > (888)
> > - *M* vowpalwabbit/loss_functions.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-54>
> > (111)
> > - *M* vowpalwabbit/loss_functions.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-55>
> > (32)
> > - *M* vowpalwabbit/lrq.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-56>
> > (350)
> > - *M* vowpalwabbit/main.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-57>
> > (106)
> > - *M* vowpalwabbit/memory.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-58>
> > (14)
> > - *M* vowpalwabbit/mf.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-59>
> > (106)
> > - *M* vowpalwabbit/multiclass.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-60>
> > (217)
> > - *M* vowpalwabbit/multiclass.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-61>
> > (26)
> > - *M* vowpalwabbit/multilabel.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-62>
> > (345)
> > - *M* vowpalwabbit/multilabel.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-63>
> > (18)
> > - *M* vowpalwabbit/multilabel_oaa.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-64>
> > (22)
> > - *M* vowpalwabbit/network.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-65>
> > (16)
> > - *M* vowpalwabbit/nn.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-66>
> > (751)
> > - *M* vowpalwabbit/noop.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-67>
> > (4)
> > - *M* vowpalwabbit/oaa.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-68>
> > (39)
> > - *M* vowpalwabbit/parse_args.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-69>
> > (1168)
> > - *M* vowpalwabbit/parse_example.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-70>
> > (195)
> > - *M* vowpalwabbit/parse_primitives.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-71>
> > (48)
> > - *M* vowpalwabbit/parse_primitives.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-72>
> > (68)
> > - *M* vowpalwabbit/parse_regressor.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-73>
> > (537)
> > - *M* vowpalwabbit/parser.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-74>
> > (1294)
> > - *M* vowpalwabbit/parser.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-75>
> > (6)
> > - *M* vowpalwabbit/print.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-76>
> > (34)
> > - *M* vowpalwabbit/rand48.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-77>
> > (8)
> > - *M* vowpalwabbit/scorer.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-78>
> > (56)
> > - *M* vowpalwabbit/search.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-79>
> > (4598)
> > - *M* vowpalwabbit/search.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-80>
> > (611)
> > - *M* vowpalwabbit/search_dep_parser.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-81>
> > (692)
> > - *M* vowpalwabbit/search_dep_parser.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-82>
> > (10)
> > - *M* vowpalwabbit/search_entityrelationtask.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-83>
> > (620)
> > - *M* vowpalwabbit/search_entityrelationtask.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-84>
> > (8)
> > - *M* vowpalwabbit/search_graph.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-85>
> > (643)
> > - *M* vowpalwabbit/search_graph.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-86>
> > (12)
> > - *M* vowpalwabbit/search_hooktask.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-87>
> > (80)
> > - *M* vowpalwabbit/search_hooktask.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-88>
> > (40)
> > - *M* vowpalwabbit/search_meta.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-89>
> > (393)
> > - *M* vowpalwabbit/search_multiclasstask.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-90>
> > (80)
> > - *M* vowpalwabbit/search_multiclasstask.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-91>
> > (8)
> > - *M* vowpalwabbit/search_sequencetask.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-92>
> > (0)
> > - *I* vowpalwabbit/search_sequencetask.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-93>
> > (0)
> > - *I* vowpalwabbit/sender.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-94>
> > (0)
> > - *I* vowpalwabbit/simple_label.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-95>
> > (0)
> > - *I* vowpalwabbit/stagewise_poly.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-96>
> > (0)
> > - *I* vowpalwabbit/svrg.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-97>
> > (0)
> > - *I* vowpalwabbit/topk.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-98>
> > (0)
> > - *I* vowpalwabbit/unique_sort.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-99>
> > (0)
> > - *I* vowpalwabbit/v_array.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-100>
> > (0)
> > - *I* vowpalwabbit/v_hashmap.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-101>
> > (0)
> > - *I* vowpalwabbit/vw.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-102>
> > (0)
> > - *I* vowpalwabbit/vw_exception.cc
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-103>
> > (0)
> > - *I* vowpalwabbit/vw_exception.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-104>
> > (0)
> > - *I* vowpalwabbit/vwdll.h
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770/files#diff-105>
> > (0)
> >
> > Patch Links:
> >
> > - https://github.com/JohnLangford/vowpal_wabbit/pull/770.patch
> > - https://github.com/JohnLangford/vowpal_wabbit/pull/770.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/JohnLangford/vowpal_wabbit/pull/770>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JohnLangford/vowpal_wabbit/pull/770#issuecomment-137217242>
> .
>



-- 
Sharat Chikkerur
"We are the way for the cosmos to know itself." - Carl Sagan

**Comment by martinpopel** [comment]
> how do we enforce it in the future?

I think it is not necessary to *enforce* it. I hope people will see the unified style and setup their editors accordingly (either via [editorconfig](http://editorconfig.org/) plugin or manually -- at least the 2-space indentation). And if not -- never mind: someone can run `astyle`, say, once per year (or before each release).

> emacs and visualstudio don't use that by default

There is an editorconfig plugin for [Emacs](https://github.com/editorconfig/editorconfig-emacs#readme), [Visual Studio](https://github.com/editorconfig/editorconfig-visualstudio#readme) and [many other editors](http://editorconfig.org/#download).

> but the benefits of consistency are minor

As described in #769, the mixed TAB+space indentation is evil (similarly bad as unintuitive naming).

> There is also the 'which style' question w.r.t. the current patch

The current pull request does not unify bracketing style (I would slightly prefer to unify also the bracketing style, but I didn't want  to do it in this commit without previous discussion). I tried to normalize only the indentation and lineend=linux, ie. only whitespace, but it seems that also some newlines were introduced. Does anyone know `astyle` (or another tool) options that would focus only on indentation without changing the number of lines?

> I do find having one-liners
> void add_float(float& c1, const float& c2) { c1 += c2; }
> more elegant than 3-liners.

We can try options `--keep-one-line-blocks` and `--keep-one-line-statements`.

**Comment by martinpopel** [comment]
> "people adopt" is (historically) a fail.

Of course, we cannot hope everyone will adopt the agreed style, but at least those want will have a chance.

> Can you tweak utl/new_version to have the right lines?

OK, done in #773.

**Pull request closed without merging**
