### PR TITLE
daemon-test.sh - check status code of the netcat

### PR DESCRIPTION
**Pull request by seifert**
daemon-test.sh refactor, trying to fix issue https://github.com/JohnLangford/vowpal_wabbit/issues/1271

### CODE REVIEW

**Comment by JohnLangford** [comment]
Looks good, thanks.

**Comment by arielf** [comment]
I see travis succeeded after all with this change...
I'm surprised it did (don't understand how), but glad.
Thanks again @seifert !

**Comment by seifert** [comment]
That's fantastic! Maybe `sleep 0.1`? I think, problem was that `vw` hadn't listened on port when `netcat` sent the request. So the test script waited inside the `until` infinite loop. Finally it was killed by `timeout`. More complex `until` loop now tests this situation.

**Comment by arielf** [comment]
Yes, infinite loop in the `until` is the best explanation.
The changes in `sleep`/`wait` probably weren't and only made the test slower.
Thanks again.

**Pull request merged**
