### PR TITLE
Redefine namespace param implementation (1)

### PR DESCRIPTION
**Pull request by trufanov-nok**
According to https://github.com/JohnLangford/vowpal_wabbit/issues/510
This pull request contains implementation of --redefine param.

Original proposal:

## 1. namspaces redefinition
The first thing I have implemented in my VW fork is *--redefine* parameter which allows me to rename any namespace or set of namespaces. I gave  a new namespaces to each feature of original dataset taking their names were from [a-Z] interval. Then I declared a parameter *--redefine* which takes string argument in form of *x:=n* where *x* is a list of old namespaces, *:=* is an operator and *n* is a new namespace to which they should be assigned. That allowed me to put something like following in my vw command line:

``--redefine abcdefgihjklmnoprstquwz:=L --redefine abcdegf:=a --ignore L  --q aa``

In example above we assign all our namespaces to namespace *L* and then (order is matter) reassign some of them to namespace *a*. As all features got their own namespaces the namespace *a* will contain 7 features and *L* 23-7=16. Then namespace a is used to generate quadratic features.

Why it's convenient? I can now experiment with different features used for quadratic features generation by just addition or removal literals in  `--redefine abcdegf:=a `.
On practice I wrote a bash script which started with `abcdefgihjklmnoprstquwz:=a` as a baseline and used leave-one-out with validation to find features which removal could improve the result.

This parameter also allows you to do something like

``--redefine abc:=a --ignore a --redefine def:=b --redefine klmn:=c -q bc``

All namespaces which were not redefined will be used as before - as ordinary feature.

Another thing why I'm so enthusiastic about this function is because it's very easy to implement without any performance penalties.

### CODE REVIEW

**Comment by trufanov-nok** [comment]
The `-redefine <arg>` processing has been changed
Now `<arg>` is in form `N:=S` where `:=` is operator, `N` - new namespace, `S`- list of old namespaces.  
The behaviour is following:  
`A:=abc` - redefine namespaces a, b and c as A
`ABC:=ABC` - same as above as only 1 character of N part is used
`A:=` - default namespace (' ') is redefined as A
`:=ABC` - namespaces a, b and c are redefined as default namespace (' ')
`:=` - default namespace (' ') is redefined as default namespace (' '), so no effect
`:=:` - wildcard ':' is used - all namespaces except default one (' ')  are redefined as default namespace (' ')
`:=:=` - same as above. First occurrence of operator has effect.
`:=abc:def` - same as above. S part processing will be stopped after reach `:` wildcard.  all namespaces except default one (' ')  will be redefined as default namespace (' ') at this point.
`--redefine A:= --redefine A:=:` - all namespaces including default one (' ') are redefined as A namespace.
`::=` - default namespace (' ') is redefined as namespace ':'.

**Comment by JohnLangford** [comment]
This looks good, except for one minor request: can you make ABC:=abc generate a warning?  Using that indicates someone does not understand what is going on.

**Comment by trufanov-nok** [comment]
It's done. Please check warning wording.

**Comment by JohnLangford** [comment]
Merged, thanks.

**Pull request merged**
