### PR TITLE
Documentation & Nuget ready

### PR DESCRIPTION
**Pull request by eisber**

### CODE REVIEW

**Comment by JohnLangford** [comment]
Is there a semantics to having '///' '////' or '/////'?  If not, can you reduce it to just use '//'?

**Comment by JohnLangford** [comment]
Why

 +#define _CRT_SECURE_NO_WARNINGS 
?

**Comment by eisber** [comment]
Getting rid of annoying warnings.

Markus




On Thu, Jul 2, 2015 at 9:10 AM -0700, "John" <notifications@github.com<mailto:notifications@github.com>> wrote:


Why

+#define _CRT_SECURE_NO_WARNINGS
?

-

**Comment by eisber** [comment]
Yes there is a semantic too out: /// allows for intellisense compatible documentation to be picked up. I'm getting the corresponding xml output and package it together with nuget

Markus




On Thu, Jul 2, 2015 at 9:08 AM -0700, "John" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there a semantics to having '///' '////' or '/////'? If not, can you reduce it to just use '//'?

-

**Comment by JohnLangford** [comment]
Why is 4 //// needed?  And 5?

-John

**Comment by JohnLangford** [comment]
But why not address the warnings in the code?

-John

**Comment by JohnLangford** [comment]
Ping.  (W.r.t. // vs. /// I want to know if obvious code cleanups will break something, so I must know the semantics.  W.r.t. warnings, I've almost always preferred addressing them rather than hiding them.)

**Comment by eisber** [comment]
@ documentation: https://msdn.microsoft.com/en-us/library/ms177246.aspx

Markus




On Sun, Jul 5, 2015 at 3:14 AM -0700, "John" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ping. (W.r.t. // vs. /// I want to know if obvious code cleanups will break something, so I must know the semantics. W.r.t. warnings, I've almost always preferred addressing them rather than hiding them.)

-

**Comment by JohnLangford** [comment]
The URL has no semantics for more than 3 '///'s.  Can you tweak to minimize these?

I'm not following the change here:  https://github.com/eisber/vowpal_wabbit/commit/ba485f2bc0b4981bc4c441a2cdf42aa9c8a6c422  
Can you describe what you are trying to do?

Why do we need an additional implementation of the hash function? https://github.com/eisber/vowpal_wabbit/commit/a0b0f8ffa2eea341c47099b3dcc13f61f0c62976  Seems inelegant to have two?

**Comment by eisber** [comment]
I don’t get the 3 ‘///’ issue. What part of the source do you refer too?

So for “fixed --interact in combination with –cbadf" the issue was that the namespace order changed and this broke calling code.
The new version just re-inserts the removed namespace at the same location.

@ hash: Louie and myself measured performance and we got a big improvement by not performing string marshalling, but rather staying in c# land.

Markus

**Comment by JohnLangford** [comment]
Got it w.r.t. interact.

Consider this line for example:
https://github.com/JohnLangford/vowpal_wabbit/pull/720/files#diff-20fa8b6910ad642ead90f6800cf77660R18
which has '/////'.  As far as I can tell, there is no reason to have more
than '///'?

The extra hash implementation is in C++ code though, right?  Why do you
need two C++ implementations of the same thing?

-John

**Comment by eisber** [comment]
Oh I see. That was unfinished code. It’s gone in the next drop.

The second hash is in C++/CLI. So it’s actually compiled to managed code. (e.g. this function: uint32_t hashall(String^ s, unsigned long u))

**Comment by JohnLangford** [comment]
Ok, can you remove it from the pull request?

-John

**Comment by eisber** [comment]
Sure.

**Comment by JohnLangford** [comment]
(This: 

https://github.com/JohnLangford/vowpal_wabbit/pull/720/files#diff-ebd13e93aa34dd3c861ff50a3d82fa2aR256
) is the extra hash implementation.

**Comment by eisber** [comment]
Yes. This is the C++/CLI version. Lync?

**Comment by JohnLangford** [comment]
Merged at last!

**Pull request merged**
